SELECT 
    a.USERNAME,
    a.ACCOUNT_STATUS,
    TO_CHAR(a.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED,
    a.PROFILE,
    TO_CHAR(a.EXPIRY_DATE, 'YYYY-MM-DD HH24:MI:SS') AS EXPIRY_DATE,
    TO_CHAR(a.LOCK_DATE, 'YYYY-MM-DD HH24:MI:SS') AS LOCK_DATE
FROM 
    DBA_USERS a
WHERE 
    TRUNC(a.LOCK_DATE) >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1)
    AND TRUNC(a.LOCK_DATE) <= LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1))
    AND a.ACCOUNT_STATUS NOT IN ('OPEN')
ORDER BY 
    a.LOCK_DATE DESC;