SELECT 
    USERNAME,
    ACCOUNT_STATUS,
    TO_CHAR(CREATED, 'YYYY-MM-DD HH24:MI:SS') AS CREATED,
    PROFILE,
    TO_CHAR(EXPIRY_DATE, 'YYYY-MM-DD HH24:MI:SS') AS EXPIRY_DATE,
    TO_CHAR(LOCK_DATE, 'YYYY-MM-DD HH24:MI:SS') AS LOCK_DATE,
    TO_CHAR(FECHA_INGESTA, 'YYYY-MM-DD HH24:MI:SS') AS FECHA_INGESTA
FROM 
    ADMONBD.SOX_USUARIOS_BLOQUEADOS
WHERE 
    TRUNC(LOCK_DATE) >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1)
    AND TRUNC(LOCK_DATE) <= LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1))
ORDER BY 
    LOCK_DATE DESC, USERNAME;
