SELECT 
    (SELECT NAME FROM V$DATABASE) AS base_de_datos,
    RTRIM(LTRIM(a.USERNAME)) AS usuario,
    RTRIM(LTRIM(a.ACCOUNT_STATUS)) AS estado,
    RTRIM(LTRIM(a.PROFILE)) AS perfil,
    TO_CHAR(a.CREATED, 'YYYY-MM-DD HH24:MI:SS') AS fecha_creacion,
    TO_CHAR(a.LOCK_DATE, 'YYYY-MM-DD HH24:MI:SS') AS fecha_bloqueo,
    TO_CHAR(a.EXPIRY_DATE, 'YYYY-MM-DD HH24:MI:SS') AS fecha_expiracion
FROM 
    DBA_USERS a
WHERE 
    TRUNC(a.CREATED) >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1)
    AND TRUNC(a.CREATED) <= LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1))
ORDER BY 
    a.CREATED DESC;